services:
  greenlight-db:
    image: postgres
    restart: always
    
    volumes:
      - greenlight-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: greenlight
networks:
  greenlight-network:
    driver: bridge
volumes:
  greenlight-volume: